name: "Check toncli"
on:
  workflow_dispatch:
jobs:
  check-commit:
    runs-on: ubuntu-latest
    steps:
      - id: cache
        name: Check cache
        uses: actions/cache@v3
        with:
          path: prev_commit.txt
          key: prev_commit

      - id: load_prev
        run: |
          [ "${{steps.cache.outputs.cache-hit}}" != ""] && echo "prev=$(cat prev_commit.txt)" >> $GITHUB_OUTPUT || echo "Cache not hit"

      - id: check
        name: Check commit
        run: |
          cur_commit=$(git ls-remote https://github.com/disintar/toncli master | awk '{print $1}')
          prev_commit="${{steps.load_prev.outputs.prev}}"
          [ "${cur_commit}" == "${prev_commit}" ] && echo "No update" || echo "update=${cur_commit}" > prev_commit.txt
