name: "Check toncli"
on:
  workflow_dispatch:
jobs:
  download-prev:
    runs-on: ubuntu-latest
    outputs:
      prev: ${{steps.prev.output.prev_commit}}
    steps:
      - id: prev
        name: Check previous
        uses: actions/download-artifact@v3
        with:
          name: prev_commit
          path: prev_commit.txt
      - name: Prev output
        run: echo "prev_commit=$(cat prev_commit.txt)" >> $GITHUB_OUTPUT
        
  check-commit:
    runs-on: ubuntu-latest
    outputs:
      update_required: ${{steps.check.outputs.update}}
    if: ${{ always() }}
    needs: [download-prev]
    steps:
      - id: check
        name: Check commit
        run: |
          cur_commit=$(git ls-remote https://github.com/disintar/toncli master | awk '{print $1}')
          prev_commit="${{ needs.download-prev.prev}}"
          echo $prev_commit
          echo $cur_commit
          [ "${cur_commit}" == "{$prev_commit}" ] && echo "No update" || echo "update=${cur_commit}" >> $GITHUB_OUTPUT 
  trigger-update:
    runs-on: ubuntu-latest
    needs: [check-commit]
    if: ${{ success() }}
    steps:
      - name: Save prev
        run: | 
          echo ${{needs.check-commit.update_required}}
          echo ${{needs.check-commit.update_required}} > prev_commit.txt
      - name: Upload prev
        uses: actions/upload-artifact@v3
        with:
          name: prev_commit
          path: prev_commit.txt
