name: "Check toncli"
on:
  workflow_dispatch:
jobs:
  check-commit:
    runs-on: ubuntu-latest
    steps:
      - id: toncli_cur
        name: Current commit
        run: echo "commit=$(git ls-remote https://github.com/disintar/toncli master | awk '{print $1}')" >> $GITHUB_OUTPUT
      - id: cache
        name: Check cache
        uses: actions/cache@v3
        with:
          path: prev_commit.txt
          key: steps.toncli_cur.outputs.commit

      - id: update
        if: steps.cache.outputs.cache-hit != 'true'
        name: Update commit
        run: echo ${{steps.toncli_cur.outputs.commit}} > prev_commit.txt
