name: "Check toncli"
on:
  workflow_dispatch:
jobs:
  check-commit:
    runs-on: ubuntu-latest
    env:
      API_URL: "https://api.github.com/repos/Trinketer22/func_docker/actions/workflows/test.yml/dispatches"
      HEADER_BEARER: "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}"
      HEADER_ACCEPT: "Accept: application/vnd.github+json"
      BRANCH_REF: '{"ref":"update_toncli"}'
    steps:
      - id: toncli_cur
        name: Current commit
        run: echo "commit=$(git ls-remote https://github.com/disintar/toncli master | awk '{print $1}')" >> $GITHUB_OUTPUT
      - id: cache
        name: Check cache
        uses: actions/cache@v3
        with:
          path: prev_commit.txt
          key: toncli-${{steps.toncli_cur.outputs.commit}}

      - name: Update commit
        if: steps.cache.outputs.cache-hit != 'true'
        run: echo ${{steps.toncli_cur.outputs.commit}} > prev_commit.txt

      - name: Trigger update toncli
        if: steps.cache.outputs.cache-hit != 'true'
        run: curl -v -X POST -H  $HEADER_ACCEPT -H $HEADER_BEARER $API_URL -d $BRANCH_REF  
